defaults:
  - _self_

method: n-cps

train:
  total_epochs: 250
  validation_interval: 10

init:
  _target_: trainer.NCrossPseudoSupervision
  supervised_criterion:
    _target_: torch.nn.MSELoss
  cps_loss_weight: 0.5
  optimizer:
    - _target_: torch.optim.AdamW
      _partial_: true
      lr: 0.001
      weight_decay: 0.005
  scheduler:
    - _target_: torch.optim.lr_scheduler.StepLR
      _partial_: true
      step_size: 1
      gamma: 0.975
