defaults:
  - _self_

method: supervised-ensemble

train:
  total_epochs: 250
  validation_interval: 10

init:
  _target_: trainers.supervised.SupervisedEnsemble
  supervised_criterion:
    _target_: torch.nn.MSELoss
    