defaults:
  - _self_

name: advanced_GCN

init:
  _target_: models.advanced_GCN
  _partial_: false
  num_node_features: 11
  hidden_channels: 128
  dropout: 0.05
  use_layer_norm: false  # if false uses batch norm
  use_residual: true
  use_kaiming_init: false  # Set to true to enable Kaiming He initialization (default PyTorch init often works better)