defaults:
  - _self_

name: gcn-mlp

init:
  _target_: models.GCN_MLP
  _partial_: false
  num_node_features: 11
  hidden_channels: 128
  dropout: 0
  dropout_final: 0
  use_residual: false
  norm_layer_type:
    _target_: models.NormLayerType
    value: "batch"
