defaults:
  - _self_

name: gcn

init:
  _target_: models.advanced_GCN
  _partial_: false
  num_node_features: 11
  hidden_channels: 128
  dropout: 0.05
  use_layer_norm: true  # if false uses batch norm
  use_residual: true