defaults:
  - _self_

name: miglec-ensemble

init:
  - _target_: models.miglec.GCN_GraphConv
    _partial_: false
    num_node_features: 11
    hidden_channels: 128
    dropout: 0
    dropout_final: 0
    use_residual: false
    norm_layer_type:
      _target_: models.miglec.NormLayerType
      value: "batch"
  - _target_: models.miglec.GCN
    _partial_: false
    num_node_features: 11
    hidden_channels: 128
    dropout: 0
    dropout_final: 0
    use_residual: false
    norm_layer_type:
      _target_: models.miglec.NormLayerType
      value: "batch"
