defaults:
  - _self_

_target_: logger.WandBLogger
group: ${dataset.dataset_name} # Name of the group for wandb
name: 3 layers with 128 hidden channels + newCosineAnnealingLR  # Name of the run for wandb
job_type: test
entity: tanja-pock-technical-university-of-munich
project_name: semi-supervised-ensembles
disable: false
local_dir: ./logs #Directory to save logs
