defaults:
  - _self_

_target_: logger.WandBLogger
group: ${dataset.dataset_name} # Name of the group for wandb
name: 3 layers with 128 hidden channels + newCosineAnnealingLR  # Name of the run for wandb
job_type: test
entity: DL-gr82
project_name: Tanjas runs
disable: false
local_dir: ./logs #Directory to save logs
