defaults:
  - _self_

_target_: logger.WandBLogger
group: ${dataset.dataset_name} # Name of the group for wandb
name: ${model.name}_{trainer.method}_seed=${seed} # Name of the run for wandb
job_type: test
entity: DL-gr82
project_name: semi-supervised-ensembles
disable: false
local_dir: ./logs #Directory to save logs
