defaults:
  - dataset: qm9
  - trainer: supervised-ensemble  # options: supervised-ensemble, semi-supervised-cps, n-cps
  - logger: wandb
  - model: gcn
  - _self_


seed: 0 # Random seed
device: unset # Device to use (cuda or cpu) if unset will use cuda if available
force_deterministic: False # Force deterministic algorithms
debug_mode: False # Debug mode
result_dir: ./results
compile_model: false # Whether to compile the model with torch.compile
save_model: false # Save the trained model(s) as dicts
